namespace Mando.Api.Enums;

public enum PaymentWorkflowStatus
{
    Success = 0,
    InvalidAmount = 1,
    VisitNotFound = 2,
    Forbidden = 3,
    VisitNotInProgress = 4,
    CustomerInactive = 5,
    CustomerNotFound = 6,
    NoOutstandingBalance = 7,
    PaymentAmountExceedsBalance = 8,
    PaymentNotFound = 9,
    PaymentAlreadyApproved = 10,
    PaymentAlreadyRejected = 11,
    PaymentNotPending = 12,
    RejectionReasonRequired = 13,
    InvalidConcurrencyToken = 14,
    ConcurrencyConflict = 15,
    ApprovalReviewCommentRequired = 16,
    ApprovalStaleAcknowledgementRequired = 17,
    ApprovalHighBalanceImpactAcknowledgementRequired = 18,
    ApprovalMultiplePendingAcknowledgementRequired = 19,
    ApprovalDuplicateReferenceAcknowledgementRequired = 20,
    NonCashReferenceRequiredForApproval = 21,
    RejectionCategoryRequired = 22,
    PrivilegedSelfReviewForbidden = 23,
    InvalidPaymentMethod = 24,
    NonCashReferenceRequired = 25,
    DuplicatePendingReference = 26,
    PendingPaymentsWouldExceedBalance = 27,
    DuplicateSubmission = 28,
    ReverseReasonRequired = 29,
    VoidReasonRequired = 29,
    PaymentNotApproved = 30,
    PaymentAlreadyReversed = 31,
    PaymentAlreadyVoided = 31
}
